//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceRecognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_DERS()
        {
            this.T_KEY = new HashSet<T_KEY>();
        }
    
        public string DERS_KODU { get; set; }
        public string DERS_ISMI { get; set; }
        public string DERS_AKADEMİSYENI { get; set; }
        public string DERS_BLOCK { get; set; }
        public string DERS_SINIF_KOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_KEY> T_KEY { get; set; }
    }
}
