//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceRecognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OGR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_OGR()
        {
            this.T_KEY = new HashSet<T_KEY>();
        }
    
        public long OGR_TC { get; set; }
        public long OGR_OKULNU { get; set; }
        public string OGR_ISIM { get; set; }
        public string OGR_DOGUMT { get; set; }
        public string OGR_BOLUM { get; set; }
        public string OGR_FAKULTE { get; set; }
        public string OGR_CINSIYET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_KEY> T_KEY { get; set; }
    }
}
